sudo: false
language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache
    - .phpunit

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - composer lint
  - composer test
