sudo: false
language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache
    - .phpunit

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phing
